server:
  port: 8080

spring:
  datasource:
    name: otc
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url:
      username:
      password:
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

  redis:
    host: localhost
    port: 6379
    password: yourpassword  # 如果你的Redis服务器设置了密码
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

jwt:
  secure-key: xxx
  expire-time: 86400000


tron:
  config:
    tronDomainUlr: https://api.trongrid.io
    tronDomainOnline: true
    trc20Address: TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t
    trc20Decimals: 1000000
    hexPrivateKey: e088f372ffaf11b33900e5fd369abdc64c4819386436541347bb4d9af17dd708
    ownerAddress: TA7weEqvrbyMygQmbNbFuAi2ndEBUAp45h